version: '3.6'

services:

  api:
    build: .
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    image: postgres
    ports:
      - 5403:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data